### ISSUE TITLE
Error when used install_tensorflow(method = "system")

### ISSUE THREAD

**Issue by feilx** [rstudio/tensorflow#165]
Error message as follows:
Preparing for installation (updating pip if necessary)
Requirement already up-to-date: pip in d:\software\python\lib\site-packages
Installing TensorFlow...
Collecting tensorflow
  Downloading tensorflow-1.3.0-cp35-cp35m-win_amd64.whl (25.5MB)
Exception:
Traceback (most recent call last):
  File "d:\software\python\lib\site-packages\pip\_vendor\requests\packages\urllib3\response.py", line 232, in _error_catcher
    yield
  File "d:\software\python\lib\site-packages\pip\_vendor\requests\packages\urllib3\response.py", line 314, in read
    data = self._fp.read(amt)
  File "d:\software\python\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 60, in read
    data = self.__fp.read(amt)
  File "d:\software\python\lib\http\client.py", line 433, in read
    n = self.readinto(b)
  File "d:\software\python\lib\http\client.py", line 473, in readinto
    n = self.fp.readinto(b)
  File "d:\software\python\lib\socket.py", line 571, in readinto
    return self._sock.recv_into(b)
  File "d:\software\python\lib\ssl.py", line 924, in recv_into
    return self.read(nbytes, buffer)
  File "d:\software\python\lib\ssl.py", line 786, in read
    return self._sslobj.read(len, buffer)
  File "d:\software\python\lib\ssl.py", line 570, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\software\python\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "d:\software\python\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "d:\software\python\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "d:\software\python\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "d:\software\python\lib\site-packages\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "d:\software\python\lib\site-packages\pip\download.py", line 659, in unpack_http_url
    hashes)
  File "d:\software\python\lib\site-packages\pip\download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "d:\software\python\lib\site-packages\pip\download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "d:\software\python\lib\site-packages\pip\utils\hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "d:\software\python\lib\site-packages\pip\download.py", line 571, in written_chunks
    for chunk in chunks:
  File "d:\software\python\lib\site-packages\pip\utils\ui.py", line 139, in iter
    for x in it:
  File "d:\software\python\lib\site-packages\pip\download.py", line 560, in resp_read
    decode_content=False):
  File "d:\software\python\lib\site-packages\pip\_vendor\requests\packages\urllib3\response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "d:\software\python\lib\site-packages\pip\_vendor\requests\packages\urllib3\response.py", line 324, in read
    flush_decoder = True
  File "d:\software\python\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "d:\software\python\lib\site-packages\pip\_vendor\requests\packages\urllib3\response.py", line 237, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.

**Comment by jjallaire** [comment]
I think that you have an SSL connectivity error between your system and pypi.python.org. Perhaps a proxy server is involved?

**Comment by feilx** [comment]
Thanks for your reply.
But I can visit pypi.python.org.
BTW,
my OS is win10 
R version is R 3.4.1 (64-bit)
python  version 3.5 (64-bit)
Any problems?

**Comment by jjallaire** [comment]
Just because you can visit it in a browser doesn't mean your R session also has the right proxy configuration to access it

**Comment by feilx** [comment]
How can it be solved?

**Comment by Gupta-Vipul** [comment]
Preparing for installation (updating pip if necessary)
Collecting pip
  Using cached pip-9.0.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 8.1.2
    Uninstalling pip-8.1.2:

But, in actual, I have the updated version of pip... any idea why this is happening?

**Comment by Gupta-Vipul** [comment]
Thanks for your input... The issue got resolved when I reinstalled the python... seems that python got corrupted...thanks again)

**Comment by jjallaire** [comment]
Great, glad things are working now!
