### ISSUE TITLE
Support installation from local .whl files

### ISSUE THREAD

**Issue by terrytangyuan** [rstudio/tensorflow#188]
It doesn't seem this is supported (correct me if I am wrong). Use case would be that I need to fix a bug on the Python end and then test the fix in R by installing a local .whl file that I built with that bug fix.

**Comment by jjallaire** [comment]
Fixed here: https://github.com/rstudio/tensorflow/commit/38f68dce76151cd415aa8c14bb5971257b028178

**Comment by terrytangyuan** [comment]
Thanks!

**Comment by terrytangyuan** [comment]
Seeing the following while trying to install the local wheel file using `tensorflow::install_tensorflow(version = "~/Downloads/tf_self_built-1.head-py2-none-any.whl")`:

```
Installing collected packages: setuptools
Successfully installed setuptools-36.6.0
Installing TensorFlow ...
Requirement '~/Downloads/tf_self_built-1.head-py2-none-any.whl' looks like a filename, but the file does not exist
Processing ./~/Downloads/tf_self_built-1.head-py2-none-any.whl
Exception:
Traceback (most recent call last):
  File "/Users/terrytangyuan/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/terrytangyuan/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/Users/terrytangyuan/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/Users/terrytangyuan/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Users/terrytangyuan/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/Users/terrytangyuan/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/pip/download.py", line 809, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/Users/terrytangyuan/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/pip/download.py", line 715, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/Users/terrytangyuan/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/pip/utils/__init__.py", line 599, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/Users/terrytangyuan/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/pip/utils/__init__.py", line 482, in unzip_file
    zipfp = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: '/Users/terrytangyuan/~/Downloads/tf_self_built-1.head-py2-none-any.whl'
Error: Error 2 occurred installing TensorFlow
```
Looks like the file name got changed from the process, e.g. `/Users/terrytangyuan/` is prepended?

**Comment by jjallaire** [comment]
Thanks! Fixed here: https://github.com/rstudio/tensorflow/commit/e519e5207c8bef33189369b0128df0297a995717
