### ISSUE TITLE
TensorFlow GPU installation fails

### ISSUE THREAD

**Issue by andrie** [rstudio/tensorflow#239]
tl;dr

I get install time and runtime error when trying to configure TensorFlow with GPU on AWS running Ubuntu 16.04

Install time:

```
coremltools 0.8 has requirement six==1.10.0, but you'll have six 1.11.0 which is incompatible.
```

Runtime:

```
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
```

---

Here is the detail:

Install time error:

```r
> tensorflow::install_tensorflow(version = "gpu")
```

```
Using existing virtualenv at  ~/.virtualenvs/r-tensorflow 
Upgrading pip ...
Collecting pip
  Using cached https://files.pythonhosted.org/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl
coremltools 0.8 has requirement six==1.10.0, but you'll have six 1.11.0 which is incompatible.
Installing collected packages: pip
Successfully installed pip-10.0.1
Upgrading wheel ...
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/1b/d2/22cde5ea9af055f81814f9f2545f5ed8a053eb749c08d186b369959189a8/wheel-0.31.0-py2.py3-none-any.whl
coremltools 0.8 has requirement six==1.10.0, but you'll have six 1.11.0 which is incompatible.
Installing collected packages: wheel
Successfully installed wheel-0.31.0
Upgrading setuptools ...
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/20/d7/04a0b689d3035143e2ff288f4b9ee4bf6ed80585cc121c90bfd85a1a8c2e/setuptools-39.0.1-py2.py3-none-any.whl
coremltools 0.8 has requirement six==1.10.0, but you'll have six 1.11.0 which is incompatible.
...
<snip>
...
  Using cached https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
coremltools 0.8 has requirement six==1.10.0, but you'll have six 1.11.0 which is incompatible.
Installing collected packages: astor, setuptools, six, protobuf, gast, werkzeug, futures, markdown, wheel, html5lib, numpy, bleach, tensorboard, absl-py, backports.weakref, termcolor, enum34, grpcio, pbr, funcsigs, mock, tensorflow-gpu, h5py, pyyaml, certifi, chardet, idna, urllib3, requests, Pillow, scipy
Successfully installed Pillow-5.1.0 absl-py-0.2.0 astor-0.6.2 backports.weakref-1.0.post1 bleach-1.5.0 certifi-2018.4.16 chardet-3.0.4 enum34-1.1.6 funcsigs-1.0.2 futures-3.2.0 gast-0.2.0 grpcio-1.11.0 h5py-2.7.1 html5lib-0.9999999 idna-2.6 markdown-2.6.11 mock-2.0.0 numpy-1.14.2 pbr-4.0.2 protobuf-3.5.2.post1 pyyaml-3.12 requests-2.18.4 scipy-1.0.1 setuptools-39.0.1 six-1.11.0 tensorboard-1.7.0 tensorflow-gpu-1.7.0 termcolor-1.1.0 urllib3-1.22 werkzeug-0.14.1 wheel-0.31.0
```

Runtime error:

```r
> imdb <- dataset_imdb(num_words = max_features)
```

```
/home/andrie/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Error: ImportError: Traceback (most recent call last):
  File "/home/andrie/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/andrie/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/andrie/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.
```

---
Session info:

```r
> devtools::session_info()
Session info --------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.442)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Etc/UTC                     
 date     2018-04-22                  

Packages ------------------------------------------------------------------------------------------------
 package    * version    date       source                             
 base       * 3.4.4      2018-04-22 local                              
 base64enc    0.1-3      2015-07-28 CRAN (R 3.4.4)                     
 compiler     3.4.4      2018-04-22 local                              
 datasets   * 3.4.4      2018-04-22 local                              
 devtools     1.13.5     2018-02-18 CRAN (R 3.4.4)                     
 digest       0.6.15     2018-01-28 CRAN (R 3.4.4)                     
 graphics   * 3.4.4      2018-04-22 local                              
 grDevices  * 3.4.4      2018-04-22 local                              
 grid         3.4.4      2018-04-22 local                              
 jsonlite     1.5        2017-06-01 CRAN (R 3.4.4)                     
 keras      * 2.1.5.9001 2018-04-22 Github (rstudio/keras@50bb9f5)     
 lattice      0.20-35    2017-03-25 CRAN (R 3.4.4)                     
 magrittr     1.5        2014-11-22 CRAN (R 3.4.4)                     
 Matrix       1.2-12     2017-11-30 CRAN (R 3.4.4)                     
 memoise      1.1.0      2017-04-21 CRAN (R 3.4.4)                     
 methods    * 3.4.4      2018-04-22 local                              
 R6           2.2.2      2017-06-17 CRAN (R 3.4.4)                     
 Rcpp         0.12.16    2018-03-13 CRAN (R 3.4.4)                     
 reticulate   1.6.0.9002 2018-04-22 Github (rstudio/reticulate@6603bb4)
 stats      * 3.4.4      2018-04-22 local                              
 tensorflow   1.5.0.9000 2018-04-22 Github (rstudio/tensorflow@ecc9f05)
 tfruns       1.3        2018-02-18 CRAN (R 3.4.4)                     
 tools        3.4.4      2018-04-22 local                              
 utils      * 3.4.4      2018-04-22 local                              
 whisker      0.3-2      2013-04-28 CRAN (R 3.4.4)                     
 withr        2.1.2      2018-03-15 CRAN (R 3.4.4)                     
 yaml         2.1.18     2018-03-08 CRAN (R 3.4.4)                     
 zeallot      0.1.0      2018-01-28 CRAN (R 3.4.4)       
```

**Comment by jjallaire** [comment]
I think the six version issue is a red herring here (not likely to be the reason you can't load).

The real issue has to do with CUDA versions. I believe that TF is built against CUDA 9.0 as opposed to 9.1 so you may need to install that version explicitly.

**Comment by harryprince** [comment]
TF is not supported CUDA9.1 very well. the better choice is CUDA 8.0 in industry.
