### ISSUE TITLE
ImportError: DLL load failed; Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by Gupta-Vipul** [rstudio/tensorflow#240]
Hello Team,

Tensorflow Installation in R is successfully completed, but when I try to verify installation, I get bellow error.

Error: ImportError: Traceback (most recent call last):
  File "C:\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\ANACON~1\envs\R-TENS~1\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: Eine DLL-Initialisierungsroutine ist fehlgeschlagen.

Failed to load the native TensorFlow runtime.

I have all the dependencies, path variable at place. Anyhelp would be really appreciated.

Thanks

**Comment by Gupta-Vipul** [comment]
It was due to tensorflow version incompatibility with my system hardware... the issue has been resolved.
