### ISSUE TITLE
Can't import Tensorflow (but works in Python)

### ISSUE THREAD

**Issue by sadatnfs** [rstudio/tensorflow#260]
Hi everyone, 

For some reason I am not able import Tensorflow into my R session, even though I can do that in Python, and it looks like it's a CXXABI error...

Here are some of the relevant background info:

``` library(tensorflow) ; sess = tf$Session();
Error: Python module tensorflow was not found.

Detected Python configuration:

python:         /opt/conda/bin/python
libpython:      /opt/conda/lib/libpython3.6m.so
pythonhome:     /opt/conda:/opt/conda
version:        3.6.6+ (heads/3.6:e13180bc4c, Jul 19 2018, 01:20:39)  [GCC 8.1.0]
numpy:          /opt/conda/lib/python3.6/site-packages/numpy-1.16.0.dev0+977431a-py3.6-linux-x86_64.egg/numpy
numpy_version:  1.16.0
tensorflow:     /opt/conda/lib/python3.6/site-packages/tensorflow

NOTE: Python version was forced by RETICULATE_PYTHON
```

If I try to import Tensorflow within R explicitly:
```> import('tensorflow')
Error in py_module_import(module, convert = convert) :
  ImportError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/opt/conda/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/conda/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /opt/conda/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_in```


But if I open up Python it imports:
```system('python -c "import tensorflow"')```

Any thoughts? I'm using a custom build of Tensorflow and I'm almost certain there's something with an LD_LIBRARY_PATH or something that's causing this, but I don't know where to start debugging from..

**Comment by sadatnfs** [comment]
Actually... turns out one of the main issues I had was that the `libstdc++.so` that R was picking up was hella old and so I just `update-alternatives` the newer one to higher priority and it seems to work now!
