### ISSUE TITLE
Installing Tensorflow successful, but module not found

### ISSUE THREAD

**Issue by muthu545** [rstudio/tensorflow#275]
Hi, Thank you for your time and help with the issue. 
It seems the package installation was successful. but  
when I run tf$session(), it prompts the TF module is not found. 

R-sources: 
###########
**> library(devtools)**
**> library(tensorflow)**
**> install_tensorflow()**
Preparing for installation (updating pip if necessary)
Requirement already up-to-date: pip in c:\users\manoharan\appdata\local\programs\python\python36\lib\site-packages (18.1)
Installing TensorFlow...
Collecting tensorflow==1.10.0
  Using cached 
Installing collected packages: gast, six, markdown, werkzeug, wheel, numpy, setuptools, protobuf, tensorboard, absl-py, termcolor, astor, grpcio, tensorflow, h5py, pyyaml, chardet, certifi, idna, urllib3, requests, Pillow, keras-preprocessing, scipy, keras-applications, keras, tensorflow-hub
Successfully installed Pillow-5.3.0 absl-py-0.6.0 astor-0.7.1 certifi-2018.10.15 chardet-3.0.4 gast-0.2.0 grpcio-1.16.0 h5py-2.8.0 idna-2.7 keras-2.2.4 keras-applications-1.0.6 keras-preprocessing-1.0.5 markdown-3.0.1 numpy-1.15.3 protobuf-3.6.1 pyyaml-3.13 requests-2.20.0 scipy-1.1.0 setuptools-39.1.0 six-1.11.0 tensorboard-1.11.0 tensorflow-1.11.0 tensorflow-hub-0.1.1 termcolor-1.1.0 urllib3-1.24 werkzeug-0.14.1 wheel-0.32.2
Installation of TensorFlow complete.
Installation complete.

**> reticulate::py_config()**
python:         c:\users\manoharan\appdata\local\programs\python\python36\python.exe
libpython:      c:/users/manoharan/appdata/local/programs/python/python36/python36.dll
pythonhome:     c:\users\manoharan\appdata\local\programs\python\python36
version:        3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\Manoharan\AppData\Roaming\Python\Python36\site-packages\numpy
numpy_version:  1.15.3
_tensorflow:     c:\users\manoharan\appdata\local\programs\python\python36\lib\site-packages\tensorflow\__init__.p_

python versions found: 
 c:\users\manoharan\appdata\local\programs\python\python36\python.exe
 C:\Users\Manoharan\AppData\Local\Programs\Python\Python36\\python.exe

**> sess = tf$Session()**
Error: Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 c:\Users\manoharan\AppData\Local\Programs\Python\Python36\python.exe
 C:\Users\Manoharan\AppData\Local\Programs\Python\Python36\python.exe

You can install TensorFlow using the install_tensorflow() function.

**> sessionInfo()**
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tensorflow_1.9.0.9000 usethis_1.4.0         devtools_2.0.0       

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.19           rstudioapi_0.8         whisker_0.3-2         
 [4] magrittr_1.5           pkgload_1.0.1          lattice_0.20-35       
 [7] R6_2.3.0               rlang_0.3.0            tools_3.5.1           
[10] pkgbuild_1.0.2         grid_3.5.1             sessioninfo_1.1.0     
[13] cli_1.0.1              withr_2.1.2            tfruns_1.4            
[16] remotes_2.0.1          assertthat_0.2.0       digest_0.6.18         
[19] rprojroot_1.3-2        crayon_1.3.4           processx_3.2.0        
[22] Matrix_1.2-14          callr_3.0.0            base64enc_0.1-3       
[25] fs_1.2.6               ps_1.2.0               memoise_1.1.0         
[28] glue_1.3.0             compiler_3.5.1         desc_1.2.0            
[31] backports_1.1.2        prettyunits_1.0.2      jsonlite_1.5          
[34] reticulate_1.10.0.9003

###########
Not sure what has happened here. 
so tried to see if the module could be accessed in python, 
but it throwed up another error. 

Python-sources:
###########
C:\Users\Manoharan>python
**Python 3.6.7** (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD6
4)] on win32
Type "help", "copyright", "credits" or "license" for more information.
**>>> import tensorflow as tf**
Traceback (most recent call last):
  File "c:\users\manoharan\appdata\local\programs\python\python36\lib\site-packa
ges\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "c:\users\manoharan\appdata\local\programs\python\python36\lib\importlib\
__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\manoharan\appdata\local\programs\python\python36\lib\site-packa
ges\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\manoharan\appdata\local\programs\python\python36\lib\site-packa
ges\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\manoharan\appdata\local\programs\python\python36\lib\site-packa
ges\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "c:\users\manoharan\appdata\local\programs\python\python36\lib\importlib\
__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\manoharan\appdata\local\programs\python\python36\lib\site-packa
ges\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "c:\users\manoharan\appdata\local\programs\python\python36\lib\site-packa
ges\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\manoharan\appdata\local\programs\python\python36\lib\site-packa
ges\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "c:\users\manoharan\appdata\local\programs\python\python36\lib\site-packa
ges\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "c:\users\manoharan\appdata\local\programs\python\python36\lib\importlib\
__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\manoharan\appdata\local\programs\python\python36\lib\site-packa
ges\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\manoharan\appdata\local\programs\python\python36\lib\site-packa
ges\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\manoharan\appdata\local\programs\python\python36\lib\site-packa
ges\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_he
lper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "c:\users\manoharan\appdata\local\programs\python\python36\lib\importlib\
__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
###########
System_info:

![image](https://user-images.githubusercontent.com/7774146/47467046-d5c24380-d7b9-11e8-9323-dada0431d9ec.png)

sorry I couldn't get much help searching online forums, tried to sort the error in different ways, but could  not get it fixed. If there was similar situation addressed in this forum, please redirect me there. 
Thanks again.

**Comment by skeydan** [comment]
You could try a manual install of TensorFlow as per

https://www.tensorflow.org/install/

then test if it works in Python, and then if successful direct R to use that Python installation...

**Comment by skeydan** [comment]
Update: You seem to be running into problems as described here

https://github.com/tensorflow/tensorflow/issues/11571

Perhaps any of the suggestions there can help you.

Also this script

https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c

checks TF install on Windows, and there are extensive discussions.
Perhaps you can get help there?
