### ISSUE TITLE
R can't find my installation of Tensorflow for GPU

### ISSUE THREAD

**Issue by droober** [rstudio/tensorflow#311]
After I install the Tensorflow using GPU I keep getting this error:

```
> reticulate::py_config() 
python:         C:\Users\Andrew\ANACON~1\python.exe
libpython:      C:/Users/Andrew/ANACON~1/python37.dll
pythonhome:     C:\Users\Andrew\ANACON~1
version:        3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\Andrew\ANACON~1\lib\site-packages\numpy
numpy_version:  1.15.4
tensorflow:     [NOT FOUND]
```

The install command I am running is

```
devtools::install_github("rstudio/keras")

library(keras)
install_keras(method = c("conda"),
              conda = "auto", version = "default", tensorflow = "gpu")
```

If i just do a regular CPU install of Keras 

```
devtools::install_github("rstudio/keras")

library(keras)
install_keras()
```

I get

```
> reticulate::py_config() 
python:         C:\Users\Andrew\Anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/Users/Andrew/Anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\Andrew\ANACON~1\envs\R-TENS~1
version:        3.6.7 (default, Feb 28 2019, 07:28:18) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\Andrew\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.16.2
tensorflow:     C:\Users\Andrew\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\__init__.p
```

Any help would be appreciated.  I am using Windows 10.

Edit:

I can force reticulate::py_config() to see my gpu install of tensorflow by doing
```

>library(reticulate)
>Sys.setenv(TENSORFLOW_PYTHON="C:/Users/Andrew/Anaconda3/envs/r-tensorflow/python.exe")
>use_python("C:/Users/Andrew/Anaconda3/envs/r-tensorflow/python.exe", required = T)

> reticulate::py_config() 
python:         C:/Users/Andrew/Anaconda3/envs/r-tensorflow/python.exe
libpython:      C:/Users/Andrew/Anaconda3/envs/r-tensorflow/python37.dll
pythonhome:     C:\Users\Andrew\ANACON~1\envs\R-TENS~1
version:        3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]
tensorflow:     C:\Users\Andrew\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\__init__.p

```

However when I do:
```
> reticulate::py_module_available(tensorflow)
[1] FALSE
> tensorflow::tf_config()
Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 C:\Users\Andrew\Anaconda3\envs\r-tensorflow\python.exe
 C:\Users\Andrew\Anaconda3\python.exe
 C:\Users\Andrew\Anaconda3\python.exe

You can install TensorFlow using the install_tensorflow() function.
```
Also 

```
> library(keras)
> k = backend()
```

Yields:

```
Error: Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 C:\Users\Andrew\Anaconda3\envs\r-tensorflow\python.exe

You can install TensorFlow using the install_tensorflow() function.
```

Edit 2:

A bit more info about my system:
OS: Windows 10
CPU: Intel Core i7-6700K 4ghz
GPU: Nvidia GTX 1070

Screenshot of my system PATH environment variables: https://imgur.com/a/Rucvynk
Screenshot of my user PATH environment variables: https://imgur.com/a/YPTj7ie

**Comment by dfalbel** [comment]
> ```
> > reticulate::py_config() 
> python:         C:/Users/Andrew/Anaconda3/envs/r-tensorflow/python.exe
> libpython:      C:/Users/Andrew/Anaconda3/envs/r-tensorflow/python37.dll
> pythonhome:     C:\Users\Andrew\ANACON~1\envs\R-TENS~1
> version:        3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
> Architecture:   64bit
> numpy:           [NOT FOUND]
> tensorflow:     C:\Users\Andrew\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\__init__.p
> ```

From your `py_config()` output it seems that `numpy` is not installed. Can you try installing numpy to this env? You can do:

```
reticulate::py_install(envname = "r-tensorflow", packages = "numpy")
```

**Comment by droober** [comment]
I ran 

`reticulate::py_install(envname = "r-tensorflow", packages = "numpy")`

and get

```
Solving environment: ...working... done

==> WARNING: A newer version of conda exists. <==
  current version: 4.5.12
  latest version: 4.6.9

Please update conda by running

    $ conda update -n base -c defaults conda

# All requested packages already installed.

Installation complete.
```

`py_config()` only has trouble finding numpy if I run it after I run

```
Sys.setenv(TENSORFLOW_PYTHON="C:/Users/Andrew/Anaconda3/envs/r-tensorflow/python.exe")
use_python("C:/Users/Andrew/Anaconda3/envs/r-tensorflow/python.exe", required = T)
```

`py_config()` can find find `numpy ` just fine when i dont force it to look in the r-tensorflow environment.

**Comment by dfalbel** [comment]
Can you try typing this on the windows command prompt:

```
C:/Users/Andrew/Anaconda3/envs/r-tensorflow/python.exe
```

and then try importing numpy with `import numpy`.

**Comment by droober** [comment]
Tried that and am getting the following:

```
Traceback (most recent call last):
  File "C:\Users\Andrew\Anaconda3\envs\r-tensorflow\lib\site-packages\numpy\core\__init__.py", line 40, in <module>
    from . import multiarray
  File "C:\Users\Andrew\Anaconda3\envs\r-tensorflow\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Users\Andrew\Anaconda3\envs\r-tensorflow\lib\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Andrew\Anaconda3\envs\r-tensorflow\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\Andrew\Anaconda3\envs\r-tensorflow\lib\site-packages\numpy\core\__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Users\Andrew\Anaconda3\envs\r-tensorflow\python.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.
```

**Comment by droober** [comment]
by installing an older version (1.11.0-gpu) i was able to get `reticulate::py_config() ` to see the numpy and tensorflow installation:
```
> library(tensorflow)
> library(reticulate)
> Sys.setenv(TENSORFLOW_PYTHON="C:/Users/Andrew/Anaconda3/envs/r-tensorflow/python.exe")
> use_python("C:/Users/Andrew/Anaconda3/envs/r-tensorflow/python.exe", required = T)
> reticulate::py_config()
python:         C:/Users/Andrew/Anaconda3/envs/r-tensorflow/python.exe
libpython:      C:/Users/Andrew/Anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\Andrew\ANACON~1\envs\R-TENS~1
version:        3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\Andrew\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.16.2
tensorflow:     C:\Users\Andrew\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\__init__.p
```

However `tensorflow::tf_config()` still gives me:

```
Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 C:\Users\Andrew\Anaconda3\envs\r-tensorflow\python.exe

You can install TensorFlow using the install_tensorflow() function.
```

And `keras:::keras_version()` gives me:
```
Error: Python module tensorflow.python.keras was not found.

Detected Python configuration:

python:         C:/Users/Andrew/Anaconda3/envs/r-tensorflow/python.exe
libpython:      C:/Users/Andrew/Anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\Andrew\ANACON~1\envs\R-TENS~1
version:        3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\Andrew\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.16.2
tensorflow:     C:\Users\Andrew\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\__init__.p

NOTE: Python version was forced by use_python function
```

**Comment by dfalbel** [comment]
I think a possible solution is to install TF 1.13.1, but use python 3.6.8. 
I am not sure if it's possible to be done with `install_tensorflow` but with conda you can run:

```
conda create -y --name r-tensorflow tensorflow python=3.6.8
```

I think this is related to https://github.com/ContinuumIO/anaconda-issues/issues/10628

**Comment by droober** [comment]
Ok I think I am almost there.  

I installed TF 1.13.1 gpu in R-studio with:

```
library(keras)
install_keras(method = c("conda"),
              conda = "auto", version = "default", tensorflow = "gpu")
```

Then I ran your above code from the anaconda prompt and it successfully downgraded my r-tensorflow environment to python3.6.8

I reopened R-studio and ran 

```
> tensorflow::tf_config()
TensorFlow v1.13.1 (C:\Users\Andrew\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\__init__.p)
Python v3.6 (C:/Users/Andrew/Anaconda3/envs/r-tensorflow/python.exe)
> keras:::keras_version()
[1] ‘2.2.4’

```
And

```
> Sys.setenv(TENSORFLOW_PYTHON="C:/Users/Andrew/Anaconda3/envs/r-tensorflow/python.exe")
> #use_python("C:/Users/Andrew/Anaconda3/envs/r-tensorflow/python.exe", required = T)
> reticulate::py_config()
python:         C:\Users\Andrew\Anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/Users/Andrew/Anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\Andrew\ANACON~1\envs\R-TENS~1
version:        3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\Andrew\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.16.2
tensorflow:     C:\Users\Andrew\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\__init__.p
```

However one final check I did was:

```
> library(keras)
> k = backend()
> sess = k$get_session()
2019-04-02 20:29:28.044426: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-04-02 20:29:28.046426: I tensorflow/core/common_runtime/process_util.cc:71] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance.
> sess$list_devices()
[[1]]
_DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 268435456, 15374039294046693498)
```

As you can see its displaying my CPU as the device in use.  I trained a quick model using BostonHousing and indeed my GPU never engaged during the training process.  

Any ideas what might be the issue?  Thanks a ton for all your help so far.

**Comment by dfalbel** [comment]
Oh sorry, my bad. It should be:

```
conda create -y --name r-tensorflow tensorflow-gpu python=3.6.8`
```

To install TF gpu version. Note `tensorflow-gpu` instead of just `tensorflow`.

**Comment by droober** [comment]
Looks like that did the trick!

```
> library(keras)
> k = backend()
> sess = k$get_session()
2019-04-03 07:24:22.119353: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-04-03 07:24:22.293346: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.64GiB
2019-04-03 07:24:22.293879: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-04-03 07:24:22.784181: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-03 07:24:22.784482: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-04-03 07:24:22.784679: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-04-03 07:24:22.784912: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6389 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
> sess$list_devices()
[[1]]
_DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 268435456, 4839208461430796879)

[[2]]
_DeviceAttributes(/job:localhost/replica:0/task:0/device:GPU:0, GPU, 6700198133, 11047270373236051326)
```

Now that its listing my GPU in the device list I take it I don't have to do anything special to get the models to start training on the GPU?

**Comment by dfalbel** [comment]
Glad it worked! No, It will use the GPU automatically.

**Comment by msmith01** [comment]
I get this error after following the instructions here:


```
> sess = k$get_session()
2019-07-13 22:58:51.029412: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-07-13 22:58:51.065751: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-07-13 22:58:52.624324: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1ed77740 executing computations on platform CUDA. Devices:
2019-07-13 22:58:52.624418: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla V100-PCIE-16GB, Compute Capability 7.0
2019-07-13 22:58:52.633197: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2019-07-13 22:58:52.645011: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1d332940 executing computations on platform Host. Devices:
2019-07-13 22:58:52.645055: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-07-13 22:58:52.646280: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Tesla V100-PCIE-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.38
pciBusID: 0000:3b:00.0
2019-07-13 22:58:52.646918: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64/R/lib::/lib:/usr/lib/jvm/jre/lib/amd64/server:/usr/lib/jvm/jre/lib/amd64:/usr/lib/jvm/java/lib/amd64:/usr/java/packages/lib/amd64:/lib:/usr/lib
2019-07-13 22:58:52.647010: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64/R/lib::/lib:/usr/lib/jvm/jre/lib/amd64/server:/usr/lib/jvm/jre/lib/amd64:/usr/lib/jvm/java/lib/amd64:/usr/java/packages/lib/amd64:/lib:/usr/lib
2019-07-13 22:58:52.647104: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64/R/lib::/lib:/usr/lib/jvm/jre/lib/amd64/server:/usr/lib/jvm/jre/lib/amd64:/usr/lib/jvm/java/lib/amd64:/usr/java/packages/lib/amd64:/lib:/usr/lib
2019-07-13 22:58:52.647190: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64/R/lib::/lib:/usr/lib/jvm/jre/lib/amd64/server:/usr/lib/jvm/jre/lib/amd64:/usr/lib/jvm/java/lib/amd64:/usr/java/packages/lib/amd64:/lib:/usr/lib
2019-07-13 22:58:52.647281: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64/R/lib::/lib:/usr/lib/jvm/jre/lib/amd64/server:/usr/lib/jvm/jre/lib/amd64:/usr/lib/jvm/java/lib/amd64:/usr/java/packages/lib/amd64:/lib:/usr/lib
2019-07-13 22:58:52.647364: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64/R/lib::/lib:/usr/lib/jvm/jre/lib/amd64/server:/usr/lib/jvm/jre/lib/amd64:/usr/lib/jvm/java/lib/amd64:/usr/java/packages/lib/amd64:/lib:/usr/lib
2019-07-13 22:58:52.647451: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64/R/lib::/lib:/usr/lib/jvm/jre/lib/amd64/server:/usr/lib/jvm/jre/lib/amd64:/usr/lib/jvm/java/lib/amd64:/usr/java/packages/lib/amd64:/lib:/usr/lib
2019-07-13 22:58:52.647461: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
2019-07-13 22:58:52.647485: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-13 22:58:52.647493: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-07-13 22:58:52.647503: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N
```
