### ISSUE TITLE
Problem locating TensorFlow

### ISSUE THREAD

**Issue by lazariv** [rstudio/tensorflow#353]
I have problem finding a system installation of TF. TF is found with `py_config()` but not when initializing a TF session:
```
> reticulate::use_condaenv("wmlce_env")
> library(reticulate)
> library(tensorflow)
> library(keras)
> py_config()
python:         /opt/anaconda3/envs/wmlce_env/bin/python
libpython:      /opt/anaconda3/envs/wmlce_env/lib/libpython3.6m.so
pythonhome:     /opt/anaconda3/envs/wmlce_env:/opt/anaconda3/envs/wmlce_env
version:        3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:34:02)  [GCC 7.3.0]
numpy:          /opt/anaconda3/envs/wmlce_env/lib/python3.6/site-packages/numpy
numpy_version:  1.14.5
tensorflow:     /opt/anaconda3/envs/wmlce_env/lib/python3.6/site-packages/tensorflow

python versions found:
 /opt/anaconda3/envs/wmlce_env/bin/python
 /usr/bin/python
 /usr/bin/python3
> tf_config()
Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 /opt/anaconda3/envs/wmlce_env/bin/python3.6
 /usr/bin/python2.7
 /usr/bin/python3.4

You can install TensorFlow using the install_tensorflow() function.
```
The installed version of TF is 1.14.  All packages are of the latest versions:
```
> devtools::session_info()
Session info ------------------------------------------------------------------
 setting  value
 version  R version 3.4.4 (2018-03-15)
 system   powerpc64le, linux-gnu
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 tz       Europe/Berlin
 date     2019-08-16

Packages ----------------------------------------------------------------------
 package    * version      date       source
 base       * 3.4.4        2019-01-15 local
 base64enc    0.1-3        2015-07-28 CRAN (R 3.4.0)
 compiler     3.4.4        2019-01-15 local
 datasets   * 3.4.4        2019-01-15 local
 devtools     1.13.5       2018-02-18 CRAN (R 3.4.4)
 digest       0.6.18       2018-10-10 CRAN (R 3.4.0)
 generics     0.0.2        2018-11-29 cran (@0.0.2)
 graphics   * 3.4.4        2019-01-15 local
 grDevices  * 3.4.4        2019-01-15 local
 grid         3.4.4        2019-01-15 local
 jsonlite     1.6          2018-12-07 cran (@1.6)
 keras      * 2.2.4.1.9001 2019-08-16 Github (rstudio/keras@34dc89e)
 lattice      0.20-35      2017-03-25 CRAN (R 3.4.4)
 magrittr     1.5          2014-11-22 CRAN (R 3.4.4)
 Matrix       1.2-12       2017-11-16 CRAN (R 3.4.4)
 memoise      1.1.0        2017-04-21 CRAN (R 3.4.4)
 methods    * 3.4.4        2019-01-15 local
 R6           2.4.0        2019-02-14 cran (@2.4.0)
 Rcpp         1.0.2        2019-07-25 CRAN (R 3.4.4)
 reticulate * 1.13.0-9000  2019-08-16 Github (rstudio/reticulate@96421b5)
 stats      * 3.4.4        2019-01-15 local
 tensorflow * 1.14.0.9000  2019-08-16 Github (rstudio/tensorflow@07d9bd5)
 tfruns       1.4          2018-08-25 CRAN (R 3.4.0)
 utils      * 3.4.4        2019-01-15 local
 whisker      0.3-2        2013-04-28 CRAN (R 3.4.0)
 withr        2.1.2        2018-03-15 CRAN (R 3.4.0)
 zeallot      0.1.0        2018-01-28 CRAN (R 3.4.0)

```

**Comment by skeydan** [comment]
Does Python TF - in that environment - work for you?
I.e., can you run something like

```import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

```
?

**Comment by lazariv** [comment]
@skeydan yes, it works fine

**Comment by dfalbel** [comment]
@lazariv What happens if you force the tensorflow environment using eg:

`reticulate::use_virtualenv("wmlce_env", required = TRUE)`

if it fails finding tensorflow. Can you try running:

```
reticulate::repl_python()
```

And then

```
import tensorflow as tf
```

**Comment by lazariv** [comment]
@dfalbel   This does not work. Here is the output
```
> reticulate::use_condaenv("wmlce_env", required = TRUE)
> reticulate::repl_python()
Python 3.6.8 (/opt/anaconda3/envs/wmlce_env/bin/python)
Reticulate 1.13.0.9000 REPL -- A Python interpreter in R.
>>> import tensorflow as tf;
ImportError: Traceback (most recent call last):
  File "/opt/anaconda3/envs/wmlce_env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/opt/anaconda3/envs/wmlce_env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/opt/anaconda3/envs/wmlce_env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/opt/anaconda3/envs/wmlce_env/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/anaconda3/envs/wmlce_env/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /sw/installed/GCCcore/6.4.0/lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /opt/anaconda3/envs/wmlce_env/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

It seems to be related to this #260 issue. But it is strange that this error message is not forwarded to `tf_config()`-call

**Comment by skeydan** [comment]
@lazariv can you provide the output of

1) `ldd /opt/anaconda3/envs/wmlce_env/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so`

2) `echo $LD_LIBRARY_PATH` on the command line

3) `Sys.getenv("LD_LIBRARY_PATH")` in R /Rstudio
btw: are you using RStudio Server?

4) the way you start python TF on the command line (just to make sure it doesn't use a different installation of TF, e.g. in system python?

Thanks!

**Comment by lazariv** [comment]
@skeydan 
Here is the output:
1.
```
ldd /opt/anaconda3/envs/wmlce_env/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
        linux-vdso64.so.1 =>  (0x0000200000050000)
        libtensorflow_framework.so.1 => /opt/anaconda3/envs/wmlce_env/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so.1 (0x000020001f2a0000)
        libnccl.so.2 => /opt/anaconda3/envs/wmlce_env/lib/python3.6/site-packages/tensorflow/python/../../../../libnccl.so.2 (0x00002000213d0000)
        libdl.so.2 => /usr/lib64/libdl.so.2 (0x0000200027db0000)
        libm.so.6 => /usr/lib64/libm.so.6 (0x0000200027de0000)
        libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x0000200027ed0000)
        librt.so.1 => /usr/lib64/librt.so.1 (0x0000200027f10000)
        libstdc++.so.6 => /opt/anaconda3/envs/wmlce_env/lib/python3.6/site-packages/tensorflow/python/../../../../libstdc++.so.6 (0x0000200027f40000)
        libgcc_s.so.1 => /opt/anaconda3/envs/wmlce_env/lib/python3.6/site-packages/tensorflow/python/../../../../libgcc_s.so.1 (0x00002000280f0000)
        libc.so.6 => /usr/lib64/libc.so.6 (0x0000200028130000)
        /lib64/ld64.so.2 (0x0000200000000000)
```
2.
```
echo $LD_LIBRARY_PATH
/opt/anaconda3/envs/wmlce_env/cuda/lib:/opt/anaconda3/envs/wmlce_env/lib/python3.6/site-packages/tensorflow:/sw/installed/R/3.4.4-gsolf-2018a-X11-20180131/lib64/R/lib:/sw/installed/R/3.4.4-gsolf-2018a-X11-20180131/lib64:/sw/installed/ICU/61.1-GCCcore-6.4.0/lib:/sw/installed/libsndfile/1.0.28-GCCcore-6.4.0/lib:/sw/installed/FFTW/3.3.7-gsmpi-2018a/lib:/sw/installed/NLopt/2.4.2-gsolf-2018a/lib64:/sw/installed/NLopt/2.4.2-gsolf-2018a/lib:/sw/installed/GDAL/2.2.3-gsolf-2018a-Python-3.6.4/lib:/sw/installed/libgeotiff/1.4.2-gsolf-2018a/lib:/sw/installed/PROJ/5.0.0-gsolf-2018a/lib:/sw/installed/JasPer/2.0.14-GCCcore-6.4.0/lib64:/sw/installed/GEOS/3.6.2-gsolf-2018a-Python-3.6.4/lib:/sw/installed/netCDF/4.6.0-gsolf-2018a/lib64:/sw/installed/HDF5/1.10.1-gsolf-2018a/lib:/sw/installed/Szip/2.1.1-GCCcore-6.4.0/lib:/sw/installed/Python/3.6.4-golf-2018a/lib/python3.6/site-packages/numpy-1.14.0-py3.6-linux-ppc64le.egg/numpy/core/lib:/sw/installed/Python/3.6.4-golf-2018a/lib:/sw/installed/cURL/7.58.0-GCCcore-6.4.0/lib:/sw/installed/Tk/8.6.8-GCCcore-6.4.0/lib:/sw/installed/Java/1.8.0_161-OpenJDK/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/amd64:/sw/installed/Java/1.8.0_161-OpenJDK/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/amd64/jli:/sw/installed/Java/1.8.0_161-OpenJDK/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib:/sw/installed/Java/1.8.0_161-OpenJDK/lib:/sw/installed/LibTIFF/4.0.9-GCCcore-6.4.0/lib:/sw/installed/libjpeg-turbo/1.5.3-GCCcore-6.4.0/lib:/sw/installed/SQLite/3.21.0-GCCcore-6.4.0/lib:/sw/installed/Tcl/8.6.8-GCCcore-6.4.0/lib:/sw/installed/libreadline/7.0-GCCcore-6.4.0/lib:/sw/installed/cairo/1.14.12-GCCcore-6.4.0/lib:/sw/installed/GLib/2.54.3-GCCcore-6.4.0/lib:/sw/installed/util-linux/2.31.1-GCCcore-6.4.0/lib:/sw/installed/PCRE/8.41-GCCcore-6.4.0/lib:/sw/installed/gettext/0.19.8.1-GCCcore-6.4.0-libxml2-2.9.7/lib:/sw/installed/libxml2/2.9.7-GCCcore-6.4.0/lib:/sw/installed/XZ/5.2.3-GCCcore-6.4.0/lib:/sw/installed/libffi/3.2.1-GCCcore-6.4.0/lib64:/sw/installed/libffi/3.2.1-GCCcore-6.4.0/lib:/sw/installed/pixman/0.34.0-GCCcore-6.4.0/lib:/sw/installed/libGLU/9.0.0-gsolf-2018a/lib:/sw/installed/Mesa/17.3.6-gsolf-2018a/lib:/sw/installed/LLVM/5.0.1-GCCcore-6.4.0/lib:/sw/installed/ncurses/6.0-GCCcore-6.4.0/lib:/sw/installed/libdrm/2.4.91-GCCcore-6.4.0/lib:/sw/installed/nettle/3.4-GCCcore-6.4.0/lib:/sw/installed/GMP/6.1.2-GCCcore-6.4.0/lib:/sw/installed/X11/20180131-GCCcore-6.4.0/lib:/sw/installed/fontconfig/2.12.6-GCCcore-6.4.0/lib:/sw/installed/freetype/2.9-GCCcore-6.4.0/lib:/sw/installed/libpng/1.6.34-GCCcore-6.4.0/lib:/sw/installed/zlib/1.2.11-GCCcore-6.4.0/lib:/sw/installed/expat/2.2.5-GCCcore-6.4.0/lib:/sw/installed/bzip2/1.0.6-GCCcore-6.4.0/lib:/sw/installed/ScaLAPACK/2.0.2-gsmpi-2018a-OpenBLAS-0.2.20/lib:/sw/installed/OpenBLAS/0.2.20-GCC-6.4.0-2.28/lib:/opt/ibm/spectrum_mpi/lib:/sw/installed/binutils/2.28-GCCcore-6.4.0/lib:/sw/installed/GCCcore/6.4.0/lib/gcc/powerpc64le-unknown-linux-gnu/6.4.0:/sw/installed/GCCcore/6.4.0/lib64:/sw/installed/GCCcore/6.4.0/lib:/usr/local/cuda/lib64::
```
3.  No, I use just R console:
```
 R -e "Sys.getenv('LD_LIBRARY_PATH')"

R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: powerpc64le-unknown-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Previously saved workspace restored]

> Sys.getenv('LD_LIBRARY_PATH')
[1] "/sw/installed/R/3.4.4-gsolf-2018a-X11-20180131/lib64/R/lib:/sw/installed/GCCcore/6.4.0/lib64:/sw/installed/GCCcore/6.4.0/lib:/sw/installed/OpenBLAS/0.2.20-GCC-6.4.0-2.28/lib:/sw/installed/ScaLAPACK/2.0.2-gsmpi-2018a-OpenBLAS-0.2.20/lib:/sw/installed/X11/20180131-GCCcore-6.4.0/lib:/sw/installed/Mesa/17.3.6-gsolf-2018a/lib:/sw/installed/libGLU/9.0.0-gsolf-2018a/lib:/sw/installed/cairo/1.14.12-GCCcore-6.4.0/lib:/sw/installed/libreadline/7.0-GCCcore-6.4.0/lib:/sw/installed/ncurses/6.0-GCCcore-6.4.0/lib:/sw/installed/bzip2/1.0.6-GCCcore-6.4.0/lib:/sw/installed/XZ/5.2.3-GCCcore-6.4.0/lib:/sw/installed/zlib/1.2.11-GCCcore-6.4.0/lib:/sw/installed/SQLite/3.21.0-GCCcore-6.4.0/lib:/sw/installed/PCRE/8.41-GCCcore-6.4.0/lib:/sw/installed/libpng/1.6.34-GCCcore-6.4.0/lib:/sw/installed/libjpeg-turbo/1.5.3-GCCcore-6.4.0/lib:/sw/installed/LibTIFF/4.0.9-GCCcore-6.4.0/lib:/sw/installed/Java/1.8.0_162/lib:/sw/installed/Tcl/8.6.8-GCCcore-6.4.0/lib:/sw/installed/Tk/8.6.8-GCCcore-6.4.0/lib:/sw/installed/cURL/7.58.0-GCCcore-6.4.0/lib:/sw/installed/libxml2/2.9.7-GCCcore-6.4.0/lib:/sw/installed/GDAL/2.2.3-gsolf-2018a-Python-3.6.4/lib:/sw/installed/PROJ/5.0.0-gsolf-2018a/lib:/sw/installed/GMP/6.1.2-GCCcore-6.4.0/lib:/sw/installed/NLopt/2.4.2-gsolf-2018a/lib64:/sw/installed/NLopt/2.4.2-gsolf-2018a/lib:/sw/installed/FFTW/3.3.7-gsmpi-2018a/lib:/sw/installed/libsndfile/1.0.28-GCCcore-6.4.0/lib:/sw/installed/ICU/61.1-GCCcore-6.4.0/lib:/sw/installed/HDF5/1.10.1-gsolf-2018a/lib:/software/ml/GCCcore/6.4.0/lib64:/software/ml/GCCcore/6.4.0/lib:/software/ml/OpenBLAS/0.2.20-GCC-6.4.0-2.28/lib:/software/ml/ScaLAPACK/2.0.2-gsmpi-2018a-OpenBLAS-0.2.20/lib:/software/ml/X11/20180131-GCCcore-6.4.0/lib:/software/ml/Mesa/17.3.6-gsolf-2018a/lib:/software/ml/libGLU/9.0.0-gsolf-2018a/lib:/software/ml/cairo/1.14.12-GCCcore-6.4.0/lib:/software/ml/libreadline/7.0-GCCcore-6.4.0/lib:/software/ml/ncurses/6.0-GCCcore-6.4.0/lib:/software/ml/bzip2/1.0.6-GCCcore-6.4.0/lib:/software/ml/XZ/5.2.3-GCCcore-6.4.0/lib:/software/ml/zlib/1.2.11-GCCcore-6.4.0/lib:/software/ml/SQLite/3.21.0-GCCcore-6.4.0/lib:/software/ml/PCRE/8.41-GCCcore-6.4.0/lib:/software/ml/libpng/1.6.34-GCCcore-6.4.0/lib:/software/ml/libjpeg-turbo/1.5.3-GCCcore-6.4.0/lib:/software/ml/LibTIFF/4.0.9-GCCcore-6.4.0/lib:/software/ml/Java/1.8.0_162/lib:/software/ml/Tcl/8.6.8-GCCcore-6.4.0/lib:/software/ml/Tk/8.6.8-GCCcore-6.4.0/lib:/software/ml/cURL/7.58.0-GCCcore-6.4.0/lib:/software/ml/libxml2/2.9.7-GCCcore-6.4.0/lib:/software/ml/GDAL/2.2.3-gsolf-2018a-Python-3.6.4/lib:/software/ml/PROJ/5.0.0-gsolf-2018a/lib:/software/ml/GMP/6.1.2-GCCcore-6.4.0/lib:/software/ml/NLopt/2.4.2-gsolf-2018a/lib64:/software/ml/NLopt/2.4.2-gsolf-2018a/lib:/software/ml/FFTW/3.3.7-gsmpi-2018a/lib:/software/ml/libsndfile/1.0.28-GCCcore-6.4.0/lib:/software/ml/ICU/61.1-GCCcore-6.4.0/lib:/software/ml/HDF5/1.10.1-gsolf-2018a/lib:/opt/anaconda3/envs/wmlce_env/cuda/lib:/opt/anaconda3/envs/wmlce_env/lib/python3.6/site-packages/tensorflow:/sw/installed/R/3.4.4-gsolf-2018a-X11-20180131/lib64/R/lib:/sw/installed/R/3.4.4-gsolf-2018a-X11-20180131/lib64:/sw/installed/ICU/61.1-GCCcore-6.4.0/lib:/sw/installed/libsndfile/1.0.28-GCCcore-6.4.0/lib:/sw/installed/FFTW/3.3.7-gsmpi-2018a/lib:/sw/installed/NLopt/2.4.2-gsolf-2018a/lib64:/sw/installed/NLopt/2.4.2-gsolf-2018a/lib:/sw/installed/GDAL/2.2.3-gsolf-2018a-Python-3.6.4/lib:/sw/installed/libgeotiff/1.4.2-gsolf-2018a/lib:/sw/installed/PROJ/5.0.0-gsolf-2018a/lib:/sw/installed/JasPer/2.0.14-GCCcore-6.4.0/lib64:/sw/installed/GEOS/3.6.2-gsolf-2018a-Python-3.6.4/lib:/sw/installed/netCDF/4.6.0-gsolf-2018a/lib64:/sw/installed/HDF5/1.10.1-gsolf-2018a/lib:/sw/installed/Szip/2.1.1-GCCcore-6.4.0/lib:/sw/installed/Python/3.6.4-golf-2018a/lib/python3.6/site-packages/numpy-1.14.0-py3.6-linux-ppc64le.egg/numpy/core/lib:/sw/installed/Python/3.6.4-golf-2018a/lib:/sw/installed/cURL/7.58.0-GCCcore-6.4.0/lib:/sw/installed/Tk/8.6.8-GCCcore-6.4.0/lib:/sw/installed/Java/1.8.0_161-OpenJDK/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/amd64:/sw/installed/Java/1.8.0_161-OpenJDK/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/amd64/jli:/sw/installed/Java/1.8.0_161-OpenJDK/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib:/sw/installed/Java/1.8.0_161-OpenJDK/lib:/sw/installed/LibTIFF/4.0.9-GCCcore-6.4.0/lib:/sw/installed/libjpeg-turbo/1.5.3-GCCcore-6.4.0/lib:/sw/installed/SQLite/3.21.0-GCCcore-6.4.0/lib:/sw/installed/Tcl/8.6.8-GCCcore-6.4.0/lib:/sw/installed/libreadline/7.0-GCCcore-6.4.0/lib:/sw/installed/cairo/1.14.12-GCCcore-6.4.0/lib:/sw/installed/GLib/2.54.3-GCCcore-6.4.0/lib:/sw/installed/util-linux/2.31.1-GCCcore-6.4.0/lib:/sw/installed/PCRE/8.41-GCCcore-6.4.0/lib:/sw/installed/gettext/0.19.8.1-GCCcore-6.4.0-libxml2-2.9.7/lib:/sw/installed/libxml2/2.9.7-GCCcore-6.4.0/lib:/sw/installed/XZ/5.2.3-GCCcore-6.4.0/lib:/sw/installed/libffi/3.2.1-GCCcore-6.4.0/lib64:/sw/installed/libffi/3.2.1-GCCcore-6.4.0/lib:/sw/installed/pixman/0.34.0-GCCcore-6.4.0/lib:/sw/installed/libGLU/9.0.0-gsolf-2018a/lib:/sw/installed/Mesa/17.3.6-gsolf-2018a/lib:/sw/installed/LLVM/5.0.1-GCCcore-6.4.0/lib:/sw/installed/ncurses/6.0-GCCcore-6.4.0/lib:/sw/installed/libdrm/2.4.91-GCCcore-6.4.0/lib:/sw/installed/nettle/3.4-GCCcore-6.4.0/lib:/sw/installed/GMP/6.1.2-GCCcore-6.4.0/lib:/sw/installed/X11/20180131-GCCcore-6.4.0/lib:/sw/installed/fontconfig/2.12.6-GCCcore-6.4.0/lib:/sw/installed/freetype/2.9-GCCcore-6.4.0/lib:/sw/installed/libpng/1.6.34-GCCcore-6.4.0/lib:/sw/installed/zlib/1.2.11-GCCcore-6.4.0/lib:/sw/installed/expat/2.2.5-GCCcore-6.4.0/lib:/sw/installed/bzip2/1.0.6-GCCcore-6.4.0/lib:/sw/installed/ScaLAPACK/2.0.2-gsmpi-2018a-OpenBLAS-0.2.20/lib:/sw/installed/OpenBLAS/0.2.20-GCC-6.4.0-2.28/lib:/opt/ibm/spectrum_mpi/lib:/sw/installed/binutils/2.28-GCCcore-6.4.0/lib:/sw/installed/GCCcore/6.4.0/lib/gcc/powerpc64le-unknown-linux-gnu/6.4.0:/sw/installed/GCCcore/6.4.0/lib64:/sw/installed/GCCcore/6.4.0/lib:/usr/local/cuda/lib64::"
>

```

4.  I suppose you mean this output:
```
which python
/opt/anaconda3/envs/wmlce_env/bin/python

python -c "import tensorflow as tf; print(tf.__version__)"
2019-08-22 09:34:23.272256: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.1
1.14.0-rc0

```

**Comment by skeydan** [comment]
Thanks! So it looks like TF should be using the `libstdc++` from Anaconda:

```
libstdc++.so.6 => /opt/anaconda3/envs/wmlce_env/lib/python3.6/site-packages/tensorflow/python/../../../../libstdc++.so.6 (0x0000200027f40000)
        
```

but R prepends `/sw/installed/GCCcore/6.4.0/lib64` to the search path, and so it ends up using the wrong library. 

I wonder if it would work if you prepended the right (for TF) path again before calling R?
(but not sure if this will work and whether it could stop R from working)?

```
LD_LIBRARY_PATH=/opt/anaconda3/envs/wmlce_env/lib:$LD_LIBRARY_PATH R
```

If that doesn't work, I think it would be necessary to change the setup so that R and Anaconda use the same version of the library.

**Comment by lazariv** [comment]
@skeydan  Unfortunately that does not work - the same error. 
Meanwhile I have build another R with newer GCCcore and tensorflow is loaded as expected. 

One suggestion from side: it would be great if the error would be propagated to `tf_config()`-call. This will make troubleshooting much easier.
