### ISSUE TITLE
tensorboard(log_dir) fails

### ISSUE THREAD

**Issue by quantitative-technologies** [rstudio/tensorflow#389]
> tensorboard(log_dir)

results in an error: 

Traceback (most recent call last):
  File "/home/james/.virtualenvs/r-reticulate/bin/tensorboard", line 10, in <module>
    sys.exit(run_main())
  File "/home/james/.virtualenvs/r-reticulate/lib/python3.6/site-packages/tensorboard/main.py", line 59, in run_main
    default.get_plugins() + default.get_dynamic_plugins(),
  File "/home/james/.virtualenvs/r-reticulate/lib/python3.6/site-packages/tensorboard/default.py", line 110, in get_dynamic_plugins
    for entry_point in pkg_resources.iter_entry_points('tensorboard_plugins')
  File "/home/james/.virtualenvs/r-reticulate/lib/python3.6/site-packages/tensorboard/default.py", line 110, in <listcomp>
    for entry_point in pkg_resources.iter_entry_points('tensorboard_plugins')
  File "/home/james/.virtualenvs/r-reticulate/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/home/james/.virtualenvs/r-reticulate/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/james/.virtualenvs/r-reticulate/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (grpcio 1.23.0 (/home/james/.virtualenvs/r-reticulate/lib/python3.6/site-packages), Requirement.parse('grpcio>=1.24.3'))
Error in if (tensorboard_version() < "2.0") { : 
  argument is of length zero
In addition: Warning message:
In system("tensorboard --version_tb", intern = TRUE) :
  running command 'tensorboard --version_tb' had status 1

> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8    LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] tensorflow_2.0.0  reticulate_1.14   here_0.1          tictoc_1.0        purrr_0.3.3       data.table_1.12.6
 [7] caret_6.0-84      ggplot2_3.2.1     lattice_0.20-38   keras_2.2.5.0     rlang_0.4.2       magrittr_1.5     
[13] assertthat_0.2.1  digest_0.6.22    

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.5   reshape2_1.4.3     splines_3.6.1      colorspace_1.4-1   generics_0.0.2     stats4_3.6.1      
 [7] base64enc_0.1-3    survival_2.44-1.1  prodlim_2019.11.13 ModelMetrics_1.2.2 pillar_1.4.2       glue_1.3.1        
[13] withr_2.1.2        rappdirs_0.3.1     foreach_1.4.7      plyr_1.8.4         lava_1.6.6         stringr_1.4.0     
[19] timeDate_3043.102  munsell_0.5.0      gtable_0.3.0       recipes_0.1.7      codetools_0.2-16   tfruns_1.4        
[25] class_7.3-15       Rcpp_1.0.3         backports_1.1.5    scales_1.0.0       ipred_0.9-9        jsonlite_1.6      
[31] stringi_1.4.3      dplyr_0.8.3        rprojroot_1.3-2    grid_3.6.1         tools_3.6.1        lazyeval_0.2.2    
[37] tibble_2.1.3       crayon_1.3.4       whisker_0.4        pkgconfig_2.0.3    zeallot_0.1.0      MASS_7.3-51.4     
[43] Matrix_1.2-17      lubridate_1.7.4    gower_0.2.1        rstudioapi_0.10    iterators_1.0.12   R6_2.4.1          
[49] rpart_4.1-15       nnet_7.3-12        nlme_3.1-141       compiler_3.6.1

**Comment by quantitative-technologies** [comment]
There seems to be some package conflict in the python installation. 

I activated the `r-reticulate` virtual environment, and verified that `tensorboard --version_tb` was giving an error. 

This was repaired with `pip install --upgrade grpcio`.

**Comment by dfalbel** [comment]
Great! Thanks!
