### ISSUE TITLE
Tensorboard doesn't start

### ISSUE THREAD

**Issue by tsengj** [rstudio/tensorflow#400]
What does this mean?

```
> tensorboard("logs/run_a")
Error: invalid version specification ‘2020-02-15 23:19:54.907995: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll’, ‘Traceback (most recent call last):’, ‘  File "c:\users\james\appdata\local\r-mini~1\envs\r-reti~1\lib\runpy.py", line 193, in _run_module_as_main’, ‘    "__main__", mod_spec)’, ‘  File "c:\users\james\appdata\local\r-mini~1\envs\r-reti~1\lib\runpy.py", line 85, in _run_code’, ‘    exec(code, run_globals)’, ‘  File "C:\Users\james\AppData\Local\R-MINI~1\envs\R-RETI~1\Scripts\TENSOR~1.EXE\__main__.py", line 4, in <module>’, ‘  File "c:\users\james\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages\tensorboard\main.py", line 44, in <module>’, ‘    from tensorboard.uploader import uploader_main’, ‘  File "c:\users\james\appdata\local\r-mini~1\envs\r-reti~1\lib\site-packages\tensorboard\uploader\uploader_main.py", line 30, in <module>’, ‘    import grpc’, ‘  File "c:\users\james\appdata\local\r-mini~1\e
In addition: Warning message:
In system("tensorboard --version_tb", intern = TRUE) :
  running command 'tensorboard --version_tb' had status 1
> reticulate::py_module_available('tensorboard')
[1] TRUE
> tensorflow::tf_config()
TensorFlow v2.0.0 ()
Python v3.6 (C:/Users/james/AppData/Local/r-miniconda/envs/r-reticulate/python.exe)
> reticulate::py_config()
python:         C:/Users/james/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      C:/Users/james/AppData/Local/r-miniconda/envs/r-reticulate/python36.dll
pythonhome:     C:/Users/james/AppData/Local/r-miniconda/envs/r-reticulate
version:        3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:18:16) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/james/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.18.1
> 
```

**Comment by t-kalinowski** [comment]
Hello,

The code that installs tensorflow and keras has been [refactored](https://github.com/rstudio/tensorflow/pull/476).
Please update to the latest versions of reticulate, tensorflow, and keras:
```R
install.packages("remotes")
remotes::install_github(paste0("rstudio/", c("reticulate", "tensorflow", "keras")))
reticulate::install_miniconda() # skip this if you want to self-install conda or use venv
keras::install_keras()
```

Please let us know if after updating you are still encountering installation issues:
https://github.com/rstudio/tensorflow/issues/new
