### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by christoforos-dimitropoulos** [rstudio/tensorflow#567]
I have installed R-4.2.3-arm64 on my M2 Macbook Air and then following the instructions you give for installing tensorflow. However I get this error when running the install_keras() function:

```

> keras::install_keras()
Installing: scipy, requests, Pillow, h5py, pandas, pydot
+ '/Users/christoforosdimitropoulos/Library/r-miniconda-arm64/bin/conda' 'install' '--yes' '--prefix' '/Users/christoforosdimitropoulos/miniconda3' '-c' 'conda-forge' 'scipy' 'requests' 'Pillow' 'h5py' 'pandas' 'pydot'
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

Installing: tensorflow-deps
+ '/Users/christoforosdimitropoulos/Library/r-miniconda-arm64/bin/conda' 'install' '--yes' '--prefix' '/Users/christoforosdimitropoulos/miniconda3' '-c' 'apple' '-c' 'conda-forge' 'tensorflow-deps'
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

Installing: tensorflow-macos
+ . /Users/christoforosdimitropoulos/Library/r-miniconda-arm64/bin/activate
+ conda activate '/Users/christoforosdimitropoulos/miniconda3'
+ '/Users/christoforosdimitropoulos/miniconda3/bin/python' -m pip install --upgrade --no-user 'tensorflow-macos'
Collecting tensorflow-macos
  Using cached tensorflow_macos-2.12.0-cp310-cp310-macosx_12_0_arm64.whl (200.8 MB)
Requirement already satisfied: six>=1.12.0 in /Users/christoforosdimitropoulos/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (1.16.0)
Requirement already satisfied: h5py>=2.9.0 in /Users/christoforosdimitropoulos/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (3.6.0)
Collecting tensorflow-estimator<2.13,>=2.12.0
  Using cached tensorflow_estimator-2.12.0-py2.py3-none-any.whl (440 kB)
Requirement already satisfied: typing-extensions>=3.6.6 in /Users/christoforosdimitropoulos/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (4.5.0)
Collecting wrapt<1.15,>=1.11.0
  Using cached wrapt-1.14.1-cp310-cp310-macosx_11_0_arm64.whl (35 kB)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /Users/christoforosdimitropoulos/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (1.53.0)
Requirement already satisfied: astunparse>=1.6.0 in /Users/christoforosdimitropoulos/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (1.6.3)
Requirement already satisfied: setuptools in /Users/christoforosdimitropoulos/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (67.6.1)
Requirement already satisfied: flatbuffers>=2.0 in /Users/christoforosdimitropoulos/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (23.3.3)
Requirement already satisfied: termcolor>=1.1.0 in /Users/christoforosdimitropoulos/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (2.2.0)
Collecting numpy<1.24,>=1.22
  Using cached numpy-1.23.5-cp310-cp310-macosx_11_0_arm64.whl (13.4 MB)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /Users/christoforosdimitropoulos/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in /Users/christoforosdimitropoulos/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (0.2.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /Users/christoforosdimitropoulos/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (3.3.0)
Collecting keras<2.13,>=2.12.0
  Using cached keras-2.12.0-py2.py3-none-any.whl (1.7 MB)
Requirement already satisfied: libclang>=13.0.0 in /Users/christoforosdimitropoulos/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (16.0.0)
Collecting jax>=0.3.15
  Using cached jax-0.4.8.tar.gz (1.2 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [63 lines of output]
      running dist_info
      creating /private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-modern-metadata-p9zosyi0/jax.egg-info
      writing /private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-modern-metadata-p9zosyi0/jax.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-modern-metadata-p9zosyi0/jax.egg-info/dependency_links.txt
      writing requirements to /private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-modern-metadata-p9zosyi0/jax.egg-info/requires.txt
      writing top-level names to /private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-modern-metadata-p9zosyi0/jax.egg-info/top_level.txt
      writing manifest file '/private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-modern-metadata-p9zosyi0/jax.egg-info/SOURCES.txt'
      reading manifest file '/private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-modern-metadata-p9zosyi0/jax.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      adding license file 'AUTHORS'
      writing manifest file '/private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-modern-metadata-p9zosyi0/jax.egg-info/SOURCES.txt'
      creating '/private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-modern-metadata-p9zosyi0/jax-0.4.8.dist-info'
      Traceback (most recent call last):
        File "/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-build-env-5njqoa7e/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-build-env-5njqoa7e/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 54, in <module>
        File "/private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-build-env-5njqoa7e/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-build-env-5njqoa7e/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-build-env-5njqoa7e/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-build-env-5njqoa7e/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-build-env-5njqoa7e/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-build-env-5njqoa7e/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-build-env-5njqoa7e/overlay/lib/python3.10/site-packages/setuptools/command/dist_info.py", line 103, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
        File "/private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-build-env-5njqoa7e/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 304, in get_finalized_command
          cmd_obj = self.distribution.get_command_obj(command, create)
        File "/private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-build-env-5njqoa7e/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 860, in get_command_obj
          klass = self.get_command_class(command)
        File "/private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-build-env-5njqoa7e/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 966, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
          module = import_module(match.group('module'))
        File "/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 883, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "/private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-build-env-5njqoa7e/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 28, in <module>
          from .macosx_libfile import calculate_macosx_platform_tag
        File "/private/var/folders/0t/kj42xwsd1qzchnwfn4w7v_lr0000gn/T/pip-build-env-5njqoa7e/overlay/lib/python3.10/site-packages/wheel/macosx_libfile.py", line 43, in <module>
          import ctypes
        File "/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/ctypes/__init__.py", line 8, in <module>
          from _ctypes import Union, Structure, Array
      ImportError: dlopen(/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/_ctypes.cpython-310-darwin.so, 0x0002): Library not loaded: @rpath/libffi.8.dylib
        Referenced from: <542A212F-FFBC-3955-B2DE-5DC7F70C0902> /Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/_ctypes.cpython-310-darwin.so
        Reason: tried: '/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/christoforosdimitropoulos/miniconda3/bin/../lib/libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/christoforosdimitropoulos/miniconda3/bin/../lib/libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS@rpath/libffi.8.dylib' (no such file), '/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/christoforosdimitropoulos/miniconda3/bin/../lib/libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/christoforosdimitropoulos/miniconda3/bin/../lib/libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/usr/local/lib/libffi.8.dylib' (no such file), '/usr/lib/libffi.8.dylib' (no such file, not in dyld cache)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Error: Error installing package(s): "'tensorflow-macos'"

```

Here is the info you need:
```
> reticulate::import("tensorflow")
Error in py_module_import(module, convert = convert) : 
  ImportError: dlopen(/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/_ctypes.cpython-310-darwin.so, 0x0002): Library not loaded: @rpath/libffi.8.dylib
  Referenced from: <542A212F-FFBC-3955-B2DE-5DC7F70C0902> /Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/_ctypes.cpython-310-darwin.so
<... omitted ...>i.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/christoforosdimitropoulos/miniconda3/lib/libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/usr/local/lib/libffi.8.dylib' (no such file), '/usr/lib/libffi.8.dylib' (no such file, not in dyld cache)
Run `reticulate::py_last_error()` for details.
> reticulate::py_config()
python:         /Users/christoforosdimitropoulos/miniconda3/bin/python
libpython:      /Users/christoforosdimitropoulos/miniconda3/lib/libpython3.10.dylib
pythonhome:     /Users/christoforosdimitropoulos/miniconda3:/Users/christoforosdimitropoulos/miniconda3
version:        3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:12:31) [Clang 14.0.6 ]
numpy:          /Users/christoforosdimitropoulos/miniconda3/lib/python3.10/site-packages/numpy
numpy_version:  1.23.2
tensorflow:     /Users/christoforosdimitropoulos/miniconda3/lib/python3.10/site-packages/tensorflow

NOTE: Python version was forced by RETICULATE_PYTHON_FALLBACK
> tensorflow::tf_config()
Valid installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 /Users/christoforosdimitropoulos/miniconda3/bin/python3.10

Python exception encountered:
 Traceback (most recent call last):
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 24, in <module>
    import ctypes
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
ImportError: dlopen(/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/_ctypes.cpython-310-darwin.so, 0x0002): Library not loaded: @rpath/libffi.8.dylib
  Referenced from: <542A212F-FFBC-3955-B2DE-5DC7F70C0902> /Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/_ctypes.cpython-310-darwin.so
  Reason: tried: '/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/christoforosdimitropoulos/miniconda3/lib/libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS@rpath/libffi.8.dylib' (no such file), '/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/christoforosdimitropoulos/miniconda3/lib/libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/usr/local/lib/libffi.8.dylib' (no such file), '/usr/lib/libffi.8.dylib' (no such file, not in dyld cache)


You can install TensorFlow using the install_tensorflow() function.
 
> reticulate::import("tensorflow")
Error in py_module_import(module, convert = convert) : 
  ImportError: dlopen(/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/_ctypes.cpython-310-darwin.so, 0x0002): Library not loaded: @rpath/libffi.8.dylib
  Referenced from: <542A212F-FFBC-3955-B2DE-5DC7F70C0902> /Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/_ctypes.cpython-310-darwin.so
<... omitted ...>i.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/christoforosdimitropoulos/miniconda3/lib/libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/usr/local/lib/libffi.8.dylib' (no such file), '/usr/lib/libffi.8.dylib' (no such file, not in dyld cache)
Run `reticulate::py_last_error()` for details.
> reticulate::py_last_error()

── Python Exception Message ─────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 24, in <module>
    import ctypes
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
ImportError: dlopen(/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/_ctypes.cpython-310-darwin.so, 0x0002): Library not loaded: @rpath/libffi.8.dylib
  Referenced from: <542A212F-FFBC-3955-B2DE-5DC7F70C0902> /Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/_ctypes.cpython-310-darwin.so
  Reason: tried: '/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/christoforosdimitropoulos/miniconda3/lib/libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS@rpath/libffi.8.dylib' (no such file), '/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/christoforosdimitropoulos/miniconda3/lib/python3.10/lib-dynload/../../libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/christoforosdimitropoulos/miniconda3/lib/libffi.8.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/usr/local/lib/libffi.8.dylib' (no such file), '/usr/lib/libffi.8.dylib' (no such file, not in dyld cache)

── R Traceback ──────────────────────────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─reticulate::import("tensorflow")
 2.   └─reticulate:::py_module_import(module, convert = convert)
> sessionInfo()
R version 4.2.3 (2023-03-15)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.2.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.10            rstudioapi_0.14        whisker_0.4.1          magrittr_2.0.3        
 [5] here_1.0.1             lattice_0.20-45        R6_2.5.1               rlang_1.1.0           
 [9] tools_4.2.3            pkgbuild_1.4.0         grid_4.2.3             png_0.1-8             
[13] cli_3.6.1              withr_2.5.0            keras_2.11.1           remotes_2.4.2         
[17] tfruns_1.5.1           rprojroot_2.0.3        crayon_1.5.2           tensorflow_2.11.0.9000
[21] processx_3.8.1         Matrix_1.5-3           callr_3.7.3            base64enc_0.1-3       
[25] ps_1.7.4               curl_5.0.0             zeallot_0.1.0          compiler_4.2.3        
[29] desc_1.4.2             generics_0.1.3         prettyunits_1.1.1      reticulate_1.28-9000  
```

Any clue why I get an error that I need arm64 while this is the one I have installed?

**Comment by t-kalinowski** [comment]
It appears you have the arm build of R, but the x86 build of miniconda. You can try using `reticulate::install_miniconda()` to install the arm build of minconda.
