### ISSUE TITLE
fatal error after install_tensorflow() R studio

### ISSUE THREAD

**Issue by chaosssss123** [rstudio/tensorflow#585]
fatal error after install_tensorflow(). I have tried everything, the path to python.exe is double-checked/its fine, have created a virtual environment as requested, made sure that I have sufficient space, have run it in R (not studio), nothing. R studio (and R) keep crashing , during installation, in particular after downloading a very demanding whl (around 250 mb). Any help/tips to deal with this would be greatly appreciated. thank you

**Comment by chaosssss123** [comment]
have completely reinstalled R, nothing

**Comment by t-kalinowski** [comment]
When opening the issue you many have noticed the "Installation Issue Template" with instructions for what information to include when opening an installation issue: https://github.com/rstudio/tensorflow/blob/main/.github/ISSUE_TEMPLATE/installation-issue.md


Can you please fill out the template?

**Comment by chaosssss123** [comment]
Hi , many thanks for your help, reallya prpeciated.

I tried the code you showed me but it fails again. R studio just crashes while installing keras or/amd tensorflow and there is a message saying that R has experience a fatal error and it just crashes. then i have to re-install both R and R studio to be able to re-open R studio. 
Please see below details on the diagnostics:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/anast/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/anast/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/anast/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-GB style='tab-interval:36.0pt;word-wrap:break-word'>




reticulate::py_config()   python:         C:/Users/user1/Documents/.virtualenvs/r-tensorflow/Scripts/python.exe   libpython:      C:/Users/user1/AppData/Local/r-reticulate/r-reticulate/pyenv/pyenv-win/versions/3.9.13/python39.dll   pythonhome:     C:/Users/user1/Documents/.virtualenvs/r-tensorflow   version:        3.9.13   (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]   Architecture:   64bit   numpy:           [NOT FOUND]   tensorflow:     [NOT FOUND]       NOTE: Python version was forced by import("tensorflow")   >   tensorflow::tf_config()   Valid installation of TensorFlow not found.       Python environments searched for 'tensorflow' package:    C:\Users\user1\Documents\.virtualenvs\r-tensorflow\Scripts\python.exe       Python exception encountered:    Traceback (most recent call   last):     File "C:\Users\user1\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py",   line 119, in _find_and_load_hook       return _run_hook(name,   _hook)     File "C:\Users\user1\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py",   line 93, in _run_hook       module = hook()     File "C:\Users\user1\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py",   line 117, in _hook       return _find_and_load(name,   import_)   ModuleNotFoundError: No module named 'tensorflow'           You can install TensorFlow using the install_tensorflow() function.       >   reticulate::import("tensorflow")   Error in py_module_import(module, convert = convert) :      ModuleNotFoundError: No module   named 'tensorflow'   Run `reticulate::py_last_error()` for details.   >   reticulate::py_last_error()       ── Python Exception Message ─────────────────────────────────────────────────────────────────────────────────────────────   Traceback (most recent call last):     File "C:\Users\user1\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook       return _run_hook(name,   _hook)     File "C:\Users\user1\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook       module = hook()     File "C:\Users\user1\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook       return _find_and_load(name,   import_)   ModuleNotFoundError: No module named 'tensorflow'       ── R Traceback ──────────────────────────────────────────────────────────────────────────────────────────────────────────       ▆    1. └─reticulate::import("tensorflow")    2.   └─reticulate:::py_module_import(module,   convert = convert)   >   sessionInfo()   R version 4.3.1 (2023-06-16 ucrt)   Platform: x86_64-w64-mingw32/x64 (64-bit)   Running under: Windows 10 x64 (build 19045)       Matrix products: default           locale:   [1] LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8      [3] LC_MONETARY=English_United Kingdom.utf8 LC_NUMERIC=C                              [5] LC_TIME=English_United Kingdom.utf8           time zone: Europe/London   tzcode source: internal       attached base packages:   [1] stats     graphics  grDevices utils     datasets    methods   base            other attached packages:   [1] keras_2.13.0        reticulate_1.34.0 devtools_2.4.5      usethis_2.2.2           loaded via a namespace (and not attached):    [1] rappdirs_0.3.3         generics_0.1.3         stringi_1.7.12         lattice_0.21-8         digest_0.6.33             [6] magrittr_2.0.3         grid_4.3.1             pkgload_1.3.3          fastmap_1.1.1          rprojroot_2.0.3          [11] jsonlite_1.8.7           Matrix_1.6-1.1           processx_3.8.2           whisker_0.4.1          pkgbuild_1.4.2           [16] sessioninfo_1.2.2        urlchecker_1.0.1         ps_1.7.5               tfruns_1.5.1           promises_1.2.1           [21] tensorflow_2.14.0.9000 purrr_1.0.2            cli_3.6.1              shiny_1.7.5            rlang_1.1.1              [26] crayon_1.5.2             pak_0.6.0                ellipsis_0.3.2           withr_2.5.1              remotes_2.4.2.1          [31] base64enc_0.1-3          cachem_1.0.8             tools_4.3.1              memoise_2.0.1          zeallot_0.1.0            [36] httpuv_1.6.11            here_1.0.1               curl_5.1.0               vctrs_0.6.4            R6_2.5.1                 [41] mime_0.12                png_0.1-8                lifecycle_1.0.3          stringr_1.5.0          fs_1.6.3                 [46] htmlwidgets_1.6.2        miniUI_0.1.1.1           desc_1.4.2               callr_3.7.3            later_1.3.1              [51] glue_1.6.2               profvis_0.3.8            Rcpp_1.0.11              rstudioapi_0.15.0      xtable_1.8-4             [56] htmltools_0.5.6.1        compiler_4.3.1           prettyunits_1.2.0
--
 
> | >
>



<p class=MsoNormal><o:p>&nbsp;</o:p></p>


</body>

</html>

**Comment by chaosssss123** [comment]
I just got an error message after R crashed again: 'unable to establish connection with r session when executing 'console input;'. I  dont know if this may  be helpful

**Comment by t-kalinowski** [comment]
Can you please paste the output by copy pasting directly from Rstudio Console or Terminal? It looks like you copypasted into microsoft word, and then somehow pasted in the raw XML from a ms word document into the github issue.

**Comment by chaosssss123** [comment]
> reticulate::py_config()
python:         C:/Users/User1/Documents/.virtualenvs/r-tensorflow/Scripts/python.exe
libpython:      C:/Users/User1/AppData/Local/r-reticulate/r-reticulate/pyenv/pyenv-win/versions/3.9.13/python39.dll
pythonhome:     C:/Users/User1/Documents/.virtualenvs/r-tensorflow
version:        3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]
tensorflow:     [NOT FOUND]

NOTE: Python version was forced by import("tensorflow")
> tensorflow::tf_config()
Valid installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 C:\Users\User1\Documents\.virtualenvs\r-tensorflow\Scripts\python.exe

Python exception encountered:
 Traceback (most recent call last):
  File "C:\Users\User1\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "C:\Users\User1\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "C:\Users\User1\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
ModuleNotFoundError: No module named 'tensorflow'


You can install TensorFlow using the install_tensorflow() function.
 
> reticulate::import("tensorflow")
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'tensorflow'
Run `reticulate::py_last_error()` for details.
> reticulate::py_last_error()

── Python Exception Message ─────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "C:\Users\User1\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "C:\Users\User1\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "C:\Users\User1\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
ModuleNotFoundError: No module named 'tensorflow'

── R Traceback ──────────────────────────────────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─reticulate::import("tensorflow")
 2.   └─reticulate:::py_module_import(module, convert = convert)
> sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8   
[3] LC_MONETARY=English_United Kingdom.utf8 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

time zone: Europe/London
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tensorflow_2.14.0.9000 keras_2.13.0           reticulate_1.34.0     

loaded via a namespace (and not attached):
 [1] rappdirs_0.3.3    generics_0.1.3    stringi_1.7.12    lattice_0.21-8    digest_0.6.33     magrittr_2.0.3   
 [7] grid_4.3.1        pkgload_1.3.3     fastmap_1.1.1     rprojroot_2.0.3   jsonlite_1.8.7    Matrix_1.6-1.1   
[13] processx_3.8.2    whisker_0.4.1     pkgbuild_1.4.2    sessioninfo_1.2.2 urlchecker_1.0.1  ps_1.7.5         
[19] tfruns_1.5.1      promises_1.2.1    purrr_1.0.2       cli_3.6.1         shiny_1.7.5       rlang_1.1.1      
[25] crayon_1.5.2      pak_0.6.0         ellipsis_0.3.2    withr_2.5.1       remotes_2.4.2.1   base64enc_0.1-3  
[31] cachem_1.0.8      devtools_2.4.5    tools_4.3.1       memoise_2.0.1     zeallot_0.1.0     httpuv_1.6.11    
[37] here_1.0.1        curl_5.1.0        vctrs_0.6.4       R6_2.5.1          mime_0.12         png_0.1-8        
[43] lifecycle_1.0.3   stringr_1.5.0     fs_1.6.3          htmlwidgets_1.6.2 usethis_2.2.2     miniUI_0.1.1.1   
[49] desc_1.4.2        callr_3.7.3       later_1.3.1       glue_1.6.2        profvis_0.3.8     Rcpp_1.0.11      
[55] rstudioapi_0.15.0 xtable_1.8-4      htmltools_0.5.6.1 compiler_4.3.1    prettyunits_1.2.0

**Comment by t-kalinowski** [comment]
Can you please include the output from running all the the other installation commands in the issue template?

**Comment by chaosssss123** [comment]
> install_tensorflow()
Virtual environment "r-tensorflow" removed.
Using Python: C:/Users/User1/AppData/Local/r-reticulate/r-reticulate/pyenv/pyenv-win/versions/3.9.13/python.exe
Creating virtual environment "r-tensorflow" ... 
+ "C:/Users/User1/AppData/Local/r-reticulate/r-reticulate/pyenv/pyenv-win/versions/3.9.13/python.exe" -m venv "C:/Users/User1/Documents/.virtualenvs/r-tensorflow"
Done!
Installing packages: pip, wheel, setuptools
+ "C:/Users/User1/Documents/.virtualenvs/r-tensorflow/Scripts/python.exe" -m pip install --upgrade pip wheel setuptools
Requirement already satisfied: pip in c:\users\User1\documents\.virtualenvs\r-tensorflow\lib\site-packages (22.0.4)
Collecting pip
  Downloading pip-23.3-py3-none-any.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 1.5 MB/s eta 0:00:00
Collecting wheel
  Using cached wheel-0.41.2-py3-none-any.whl (64 kB)
Requirement already satisfied: setuptools in c:\users\User1\documents\.virtualenvs\r-tensorflow\lib\site-packages (58.1.0)
Collecting setuptools
  Using cached setuptools-68.2.2-py3-none-any.whl (807 kB)
Installing collected packages: wheel, setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 58.1.0
    Uninstalling setuptools-58.1.0:
      Successfully uninstalled setuptools-58.1.0
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4
Successfully installed pip-23.3 setuptools-68.2.2 wheel-0.41.2
Virtual environment 'r-tensorflow' successfully created.
Using virtual environment "r-tensorflow" ...
+ "C:/Users/User1/Documents/.virtualenvs/r-tensorflow/Scripts/python.exe" -m pip install --upgrade --no-user "tensorflow==2.14.*"
Collecting tensorflow==2.14.*
  Downloading tensorflow-2.14.0-cp39-cp39-win_amd64.whl.metadata (3.3 kB)
Collecting tensorflow-intel==2.14.0 (from tensorflow==2.14.*)
  Downloading tensorflow_intel-2.14.0-cp39-cp39-win_amd64.whl.metadata (4.8 kB)
Collecting absl-py>=1.0.0 (from tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading absl_py-2.0.0-py3-none-any.whl.metadata (2.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting flatbuffers>=23.5.26 (from tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading flatbuffers-23.5.26-py2.py3-none-any.whl.metadata (850 bytes)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading gast-0.5.4-py3-none-any.whl (19 kB)
Collecting google-pasta>=0.1.1 (from tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
     ---------------------------------------- 57.5/57.5 kB 1.5 MB/s eta 0:00:00
Collecting h5py>=2.9.0 (from tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading h5py-3.10.0-cp39-cp39-win_amd64.whl.metadata (2.5 kB)
Collecting libclang>=13.0.0 (from tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading libclang-16.0.6-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting ml-dtypes==0.2.0 (from tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading ml_dtypes-0.2.0-cp39-cp39-win_amd64.whl.metadata (20 kB)
Collecting numpy>=1.23.5 (from tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading numpy-1.26.1-cp39-cp39-win_amd64.whl.metadata (61 kB)
     ---------------------------------------- 61.2/61.2 kB 3.2 MB/s eta 0:00:00
Collecting opt-einsum>=2.3.2 (from tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     ---------------------------------------- 65.5/65.5 kB 1.7 MB/s eta 0:00:00
Collecting packaging (from tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 (from tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading protobuf-4.24.4-cp39-cp39-win_amd64.whl.metadata (540 bytes)
Requirement already satisfied: setuptools in c:\users\User1\documents\.virtualenvs\r-tensorflow\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow==2.14.*) (68.2.2)
Collecting six>=1.12.0 (from tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting termcolor>=1.1.0 (from tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading termcolor-2.3.0-py3-none-any.whl (6.9 kB)
Collecting typing-extensions>=3.6.6 (from tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting wrapt<1.15,>=1.11.0 (from tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading wrapt-1.14.1-cp39-cp39-win_amd64.whl (35 kB)
Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading tensorflow_io_gcs_filesystem-0.31.0-cp39-cp39-win_amd64.whl (1.5 MB)
     ---------------------------------------- 1.5/1.5 MB 3.0 MB/s eta 0:00:00
Collecting grpcio<2.0,>=1.24.3 (from tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading grpcio-1.59.0-cp39-cp39-win_amd64.whl.metadata (4.2 kB)
Collecting tensorboard<2.15,>=2.14 (from tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading tensorboard-2.14.1-py3-none-any.whl.metadata (1.7 kB)
Collecting tensorflow-estimator<2.15,>=2.14.0 (from tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading tensorflow_estimator-2.14.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting keras<2.15,>=2.14.0 (from tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading keras-2.14.0-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\User1\documents\.virtualenvs\r-tensorflow\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.14.0->tensorflow==2.14.*) (0.41.2)
Collecting google-auth<3,>=1.6.3 (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading google_auth-2.23.3-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
Collecting markdown>=2.6.8 (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading Markdown-3.5-py3-none-any.whl.metadata (7.1 kB)
Collecting requests<3,>=2.21.0 (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading tensorboard_data_server-0.7.1-py3-none-any.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading werkzeug-3.0.0-py3-none-any.whl.metadata (4.1 kB)
Collecting cachetools<6.0,>=2.0.0 (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading cachetools-5.3.1-py3-none-any.whl.metadata (5.2 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)
     -------------------------------------- 181.3/181.3 kB 3.6 MB/s eta 0:00:00
Collecting rsa<5,>=3.1.4 (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading rsa-4.9-py3-none-any.whl (34 kB)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Collecting importlib-metadata>=4.4 (from markdown>=2.6.8->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading importlib_metadata-6.8.0-py3-none-any.whl.metadata (5.1 kB)
Collecting charset-normalizer<4,>=2 (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow==2.14.*)
  Downloading charset_normalizer-3.3.0-cp39-cp39-win_amd64.whl.metadata (33 kB)

and then fatal error....similar thing when installing keras

**Comment by chaosssss123** [comment]
any advice?

**Comment by chaosssss123** [comment]
i run it cmd, this is what i get:

 ---------------------------------------- 98.2/98.2 kB 2.8 MB/s eta 0:00:00
Downloading importlib_metadata-6.8.0-py3-none-any.whl (22 kB)
Downloading MarkupSafe-2.1.3-cp39-cp39-win_amd64.whl (17 kB)
Downloading urllib3-2.0.6-py3-none-any.whl (123 kB)
   ---------------------------------------- 123.8/123.8 kB 3.7 MB/s eta 0:00:00
Downloading zipp-3.17.0-py3-none-any.whl (7.4 kB)
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\User1\\AppData\\Local\\Temp\\pip-unpack-vx6rpc24\\tensorflow-2.14.0-cp39-cp39-win_amd64.whl'

WARNING: There was an error checking the latest version of pip.

**Comment by chaosssss123** [comment]
Downloading charset_normalizer-3.3.0-cp39-cp39-win_amd64.whl (98 kB)
   ---------------------------------------- 98.2/98.2 kB 5.5 MB/s eta 0:00:00
Downloading importlib_metadata-6.8.0-py3-none-any.whl (22 kB)
Downloading MarkupSafe-2.1.3-cp39-cp39-win_amd64.whl (17 kB)
Downloading urllib3-2.0.6-py3-none-any.whl (123 kB)
   ---------------------------------------- 123.8/123.8 kB 7.1 MB/s eta 0:00:00
Downloading zipp-3.17.0-py3-none-any.whl (7.4 kB)
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\User1\\AppData\\Local\\Temp\\pip-unpack-bi8sc5t8\\tensorflow-2.14.0-cp39-cp39-win_amd64.whl'

WARNING: There was an error checking the latest version of pip.

**Comment by t-kalinowski** [comment]
If you run a `pip install` command in cmd.exe, do you get the same error?
```cmd
"C:/Users/User1/Documents/.virtualenvs/r-tensorflow/Scripts/python.exe" -m pip install --upgrade --no-user tensorflow
```

**Comment by chaosssss123** [comment]
thank you.
i get an error unexpected symbol. somethign is wrong with the code line? also, when do i run this? instead of using : tensorflow::install_tensorflow() , I run this command?

**Comment by t-kalinowski** [comment]
Are you running in the Windows application named "cmd.exe", or in Rstudio console?

**Comment by chaosssss123** [comment]
cmd

**Comment by chaosssss123** [comment]
cmd s not working. anything to suggest in R studio to solve this?

**Comment by chaosssss123** [comment]
have read about isntalling cuda, or downgrading tensorflow etc, i have tried everything, nothing works

**Comment by chaosssss123** [comment]
?????????

**Comment by chaosssss123** [comment]
> If you run a `pip install` command in cmd.exe, do you get the same error?
> 
> ```batchfile
> "C:/Users/User1/Documents/.virtualenvs/r-tensorflow/Scripts/python.exe" -m pip install --upgrade --no-user tensorflow
> ```

does not work i get an error message. i need to fix this i R or R studio

**Comment by chaosssss123** [comment]
I rerun in cmd, it does install TensorFlow without crashing but then cmd gets back to C:\Users\User1, so typing again C:/PROGRA~1/R/R-43~1.1/bin/R gets an error. I then realised that this happens because after installing tensorflow R crashed again even if i installed it within cmd. So, again we are back  to the same, vicious cycle. cmd does nto solve the problem. something is preventing r studio /r from isntalling keras/tensorflow.

**Comment by t-kalinowski** [comment]
If you're encountering an error when running the system command `python -m pip install tensorflow` in cmd.exe, then I don't think there is anything the R package can do to fix that. 

It could be any number of issues:
-  Maybe there isn't enough RAM on your machine to unpack the pre-built whl file?
-  Maybe your machine is managed with IT policies that prohibit pip from utilizing the temp folder? 
- Maybe your home directory is on a network drive with very high latency and pip can't handle that? 
- Maybe any one of 20 other things? 

It is difficult to diagnose without more information, and also, I believe the error you're experiencing is extremely uncommon. The R function `install_tensorflow()` works without any issues for the vast majority of people. 

My advice is to find a local expert who can help you navigate this unique situation. Additionally, if you get tensorflow working in a Python installation on your machine, you can always point R at it by setting the env var `RETICULATE_PYTHON`. 

Also, please stop spamming across the different repos with the same issue.
